### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by privatenumber** [privatenumber/tsx#267]
# Roadmap

### Breaking changes
- tsconfig.json to be applied to all imported files https://github.com/privatenumber/tsx/issues/393#issuecomment-1816134331
- tsconfig.json to be discovered by closest `tsconfig.json` from entry-file (diverges from tsc behavior but makes more sense with tsx)
- Disable source-maps by default https://github.com/privatenumber/tsx/discussions/386
- Review and remove unused exports entry points
  - Delete unused `repl.ts`
- Rename `esm` to `hook` as Node adds support for CJS in their Hooks API (https://github.com/nodejs/node/pull/47999)

## v4
We're close to hitting 2 million downloads a month on npm 🎉 Thank you everyone! ❤️

I'd like to take this opportunity to communicate what I have in mind next. If there's anything that I missed or needs to be prioritized, please feel free to comment.

## ESM Interoperability
- Interop CommonJS from ESM https://github.com/esbuild-kit/tsx/issues/67

## Optimize dependency transformations
- [x] https://github.com/esbuild-kit/tsx/issues/167
- [x] https://github.com/esbuild-kit/tsx/issues/228

## Node v20 support
- [x] https://github.com/esbuild-kit/tsx/issues/236
- [x] https://github.com/esbuild-kit/tsx/issues/246
- [x] https://github.com/esbuild-kit/tsx/issues/291

## TypeScript parity

- TypeScript file matching
  - [ ] https://github.com/esbuild-kit/tsx/issues/135

- TypeScript resolver
  - [x] https://github.com/esbuild-kit/tsx/issues/112
  - [x] https://github.com/esbuild-kit/tsx/issues/74
  - [ ] https://github.com/esbuild-kit/tsx/issues/59

### tsconfig.json
- [ ] Support multiple tsconfig.json files https://github.com/esbuild-kit/tsx/issues/265
- [ ] Support `jsconfig.json` https://github.com/esbuild-kit/tsx/issues/259
- [ ] Monorepo support (multiple TypeScript projects) https://github.com/esbuild-kit/tsx/issues/159 https://github.com/esbuild-kit/tsx/issues/96

## VSCode debugging
- [x] Add documentation for debugging in VSCode. I believe this is technically already possible, and is just a matter of setting it up. https://github.com/privatenumber/tsx/pull/399

## Watch mode
- [x] Consider changing watcher https://github.com/esbuild-kit/tsx/issues/246
- [x] Wait for child process to exit https://github.com/esbuild-kit/tsx/pull/244
- [ ] Log which files has changed before reloading https://github.com/esbuild-kit/tsx/issues/218
- [ ] Change reload command to Ctrl+R so users can still use the stdin
- [ ] Align with Node.js `--watch` flag?

## REPL
- [ ] Support TypeScript in `--eval` flag https://github.com/esbuild-kit/tsx/issues/162

## Testing
A lot of the tests in tsx are re-testing what's tested in the specific loaders. The scope of the tests can be significantly smaller and focus more on what's not tested.

## Node.js support
- [x] Drop Node.js v12, v14, v16

## Branding
- Make a website/landing page
- A lot of people are confused when tsx does not have parity with esbuild. They're given the impression that tsx is an esbuild runtime, but tsx actually only uses esbuild to transform TypeScript to JS. The branding needs to change so it's less about esbuild and more about TypeScript.

## Monorepo
- [x] I'm not a big fan of monorepos but it might make it easier for others to contribute if the loaders were in the same repo. However, I have some reservations about testing because there's a ton for each component.
	- Completed by consolidating to one repo without using a monorepo

## Sponsorships

I work on this project on my personal time which is not sustainable. If you find this project useful, please consider showing your appreciation by [sponsoring me](https://github.com/sponsors/privatenumber). Thank you! ❤️

**Comment by AshotN** [comment]
Are there any plans to add some docs to explain how to get debugging working with WebStorm?

**Comment by waynebloss** [comment]
RE: Branding - Would you consider renaming the project to something that is easier to search for? It's very, very difficult to find answers or writings surrounding this project due to the naming conflict with the much more well known `tsx`.

**Comment by privatenumber** [comment]
Locking thread to prevent off-topic discussions.

If there's a bug, please file it. If you have a question, want to propose an idea, etc, [start a Discussion](https://github.com/pvtnbr/tsx/discussions) (sponsors only).

**Comment by privatenumber** [comment]
Moving this thread to the private development repo https://github.com/pvtnbr/tsx to plan v5
