### ISSUE TITLE
`import.meta.resolve(pathToDirectory)` returns a different result when running with `tsx` compared to `node`

### ISSUE THREAD

**Issue by haines** [privatenumber/tsx#480]
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://github.com/haines/tsx-import-meta-resolve

### Version

v4.7.1

### Node.js version

v20.11.1

### Package manager

npm

### Operating system

macOS

### Problem & Expected behavior

I want to resolve the path to a directory within one of my dependencies. I'm using ESM so I call [`import.meta.resolve`](https://nodejs.org/api/esm.html#importmetaresolvespecifier).

For example,

```typescript
console.log(import.meta.resolve("typescript/lib"));
```

Doing this in `node` returns a file URL with the path to the directory:

```
file:///tsx-import-meta-resolve/node_modules/typescript/lib
```

However, when I run the script via `tsx`, I unexpectedly get a file URL with the path to `index.js` within the directory (which is a non-existent file):

```
file:///tsx-import-meta-resolve/node_modules/typescript/lib/index.js
```

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project
